export const BUY_ITEM = 'BUY_ITEM';
export const REMOVE_FEATURE = 'REMOVE_FEATURE';
export const FETCH_CAR_IMAGE_START = 'FETCH_CAR_IMAGE_START';
export const FETCH_CAR_IMAGE_SUCCESS = 'FETCH_CAR_IMAGE_SUCCESS';
export const FETCH_CAR_IMAGE_FAIL = 'FETCH_CAR_IMAGE_FAIL';